"""add social, queue, contexts, analytics, and execution logs tables

Revision ID: 481217af9efd
Revises: 6072d23c6cdf
Create Date: 2026-06-02 06:58:52.346274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '481217af9efd'
down_revision: Union[str, Sequence[str], None] = '6072d23c6cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_brand_contexts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('brand_bio', sa.Text(), nullable=False),
    sa.Column('preferred_tones', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('banned_keywords', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('social_accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('account_handle', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.CheckConstraint("platform IN ('facebook', 'x', 'linkedin', 'instagram', 'tiktok')", name='check_valid_social_platform'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_execution_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('trigger_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('SUCCESS', 'FAILURE')", name='check_valid_log_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_execution_logs_status'), 'system_execution_logs', ['status'], unique=False)
    op.create_index(op.f('ix_system_execution_logs_task_name'), 'system_execution_logs', ['task_name'], unique=False)
    op.create_table('scheduled_posts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('social_account_id', sa.UUID(), nullable=False),
    sa.Column('platform_post_id', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('scheduled_for', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('live_url', sa.String(length=512), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'PENDING', 'PUBLISHED', 'FAILED')", name='check_valid_post_status'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_posts_platform_post_id'), 'scheduled_posts', ['platform_post_id'], unique=True)
    op.create_index(op.f('ix_scheduled_posts_scheduled_for'), 'scheduled_posts', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_status'), 'scheduled_posts', ['status'], unique=False)
    op.create_table('post_analytics',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('likes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('shares', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_synced_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('comments >= 0', name='check_comments_non_negative'),
    sa.CheckConstraint('likes >= 0', name='check_likes_non_negative'),
    sa.CheckConstraint('shares >= 0', name='check_shares_non_negative'),
    sa.ForeignKeyConstraint(['post_id'], ['scheduled_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_analytics')
    op.drop_index(op.f('ix_scheduled_posts_status'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_scheduled_for'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_platform_post_id'), table_name='scheduled_posts')
    op.drop_table('scheduled_posts')
    op.drop_index(op.f('ix_system_execution_logs_task_name'), table_name='system_execution_logs')
    op.drop_index(op.f('ix_system_execution_logs_status'), table_name='system_execution_logs')
    op.drop_table('system_execution_logs')
    op.drop_table('social_accounts')
    op.drop_table('ai_brand_contexts')
    # ### end Alembic commands ###
